global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: prometheus

storage:
  tsdb:
    out_of_order_time_window: 30m

scrape_configs:
  - job_name: data-transfer
    static_configs:
      - targets:
        - 'api:8089'
  - job_name: jaeger
    static_configs:
      - targets:
          - 'jaeger:8888'
          - 'jaeger:8889'

rule_files:
  - alerting-rules.yml
