{
 "title": "Data Transfer Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Service Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Service Load",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "system_cpu_count{job=\"$service\"}",
       "legendFormat": "CPUs"
      },
      {
       "expr": "system_load_average_1m{job=\"$service\"}",
       "legendFormat": "Load-1m"
      }
     ]
    },
    {
     "title": "Service CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"$service\"}",
       "legendFormat": "System"
      },
      {
       "expr": "process_cpu_usage{job=\"$service\"}",
       "legendFormat": "Process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{job=\"$service\"}[1h])",
       "legendFormat": "Process-1h"
      }
     ]
    },
    {
     "title": "Service Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$service\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$service\"})",
       "legendFormat": "Committed"
      }
     ]
    },
    {
     "title": "Used Heap Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$service\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=\"$service\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Used Non-Heap Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$service\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=\"$service\", area=\"nonheap\"})"
      }
     ]
    }
   ]
  },
  { "title": "Service Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$service\", uri!~\"/swagger.*|/openapi\"}[1m]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$service\", uri=\"/transfers\", method=\"POST\", outcome=\"SUCCESS\"}[1m]))",
     "legendFormat": "Transfers"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$service\", uri!~\"/swagger.*|/openapi\"}[2m]))",
     "legendFormat": "Rate-1m"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds{job=\"$service\", uri!~\"/swagger.*|/openapi\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max(http_server_requests_seconds{job=\"$service\", uri!~\"/swagger.*|/openapi\", quantile=\"0.95\"})",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max(http_server_requests_seconds_max{job=\"$service\", uri!~\"/swagger.*|/openapi\"})",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"$service\", uri!~\"/swagger.*|/openapi\", outcome!=\"SUCCESS\"}[1m]))*100/sum(increase(http_server_requests_seconds_count{job=\"$service\", uri!~\"/swagger.*|/openapi\"}[1m]))",
     "legendFormat": "Percent of requests failing"
    }
   ]
  },
  {
   "title": "Status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{job=\"$service\", uri!~\"/swagger.*|/openapi\"}[1m]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Service Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logged Traces",
     "type": "logs",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"unknown_service\"} | filename =~ `$service-$instance.json.*` | json | line_format `span:{{.mdc_spanId}} trace:{{.mdc_traceId}} sequence:{{.sequence}} | {{.message}} | {{.loggerName}}`"
      }
     ]
    }
   ]
  }
 ]
}